import 'models/lesson.dart';
import 'models/vocab.dart';

const lesson = [
  Lesson(id: '1', title: 'Lesson 1'),
  Lesson(id: '2', title: 'Lesson 2'),
  Lesson(id: '3', title: 'Lesson 3'),
  Lesson(id: '4', title: 'Lesson 4'),
  Lesson(id: '5', title: 'Lesson 5'),
];

const vocabulary = [
  Vocab(
    lessonId: '1',
    count: 1,
    word: '발써',
    pronounce: 'Beol.sseo',
    meaning: 'Already (adv.)',
    sentence: ['너 발써 끝냈니? 재빠르구나!', 'Have you finished already? You are fast!'],
  ),
  Vocab(
    lessonId: '1',
    count: 2,
    word: '폭풍',
    pronounce: 'Pok.pung',
    meaning: 'Storm (n.)',
    sentence: ['폭풍이 곧 잠잠해질 거예요.', 'The storm will blow over soon.'],
  ),
  Vocab(
    lessonId: '1',
    count: 3,
    word: '개구리',
    pronounce: 'Gae.gu.ri',
    meaning: 'Frog (n.)',
    sentence: ['연못에 개구리 한 마리가 있어요.', 'There is a frod in the pond.'],
  ),
  Vocab(
    lessonId: '1',
    count: 4,
    word: '포크',
    pronounce: 'Po.keu',
    meaning: 'Fork (n.)',
    sentence: ['나이프와 포크가 냅킨 위에 있다.', 'The knife and fork are on the napkin.'],
  ),
  Vocab(
    lessonId: '1',
    count: 5,
    word: '면',
    pronounce: 'Myeon',
    meaning: 'Cotton (n.)',
    sentence: ['이 티셔츠는 면으로 만들어졌다.', 'This t-shirt is made of cotton.'],
  ),
  Vocab(
    lessonId: '1',
    count: 6,
    word: '어부',
    pronounce: 'Eo.bu',
    meaning: 'Fisherman (n.)',
    sentence: [
      '저 어부는 거의 매일 고기잡이를 간다.',
      'That fisherman goes fishing almost everyday.'
    ],
  ),
  Vocab(
    lessonId: '1',
    count: 7,
    word: '속',
    pronounce: 'Sok',
    meaning: 'Inside (n.)',
    sentence: ['그녀는 물속으로 뛰어들었다.', 'She jumped into the water.'],
  ),
  Vocab(
    lessonId: '1',
    count: 8,
    word: '지키다',
    pronounce: 'Ji.ki.da',
    meaning: 'Guard ; protect (v.)',
    sentence: ['그들은 대개 정문을 지켜요.', 'They usually guard the front gate.'],
  ),
  Vocab(
    lessonId: '1',
    count: 9,
    word: '손목',
    pronounce: 'Son.mork',
    meaning: 'Wrist (n.)',
    sentence: ['그녀는 왼족 손목을 삐었습니다.', 'She is sprained her left wrist.'],
  ),
  Vocab(
    lessonId: '1',
    count: 10,
    word: '눈썹',
    pronounce: 'Nun.sseop',
    meaning: 'Eyebrow (n.)',
    sentence: ['그 소년은 눈썹이 짙다.', 'The boy has thick eyebrows.'],
  ),
  Vocab(
    lessonId: '2',
    count: 1,
    word: '기자',
    pronounce: 'Gi.ja',
    meaning: 'Reporter ; journalist (n.)',
    sentence: [
      '사건 현장으로 기자들이 몰려들었다.',
      'Reporters rushed to the scene of the incident.'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 2,
    word: '시',
    pronounce: 'Si',
    meaning: 'Poem (n.)',
    sentence: ['이 시를 이해하시겠습니까?', 'Can you figure out this poem?'],
  ),
  Vocab(
    lessonId: '2',
    count: 3,
    word: '병',
    pronounce: 'Byeong',
    meaning: 'Disease ; illness (n.)',
    sentence: [
      '2살 때, 그녀는 병을 앓았다.',
      'When she was 2 years old, she suffered from an illness.'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 4,
    word: '소원',
    pronounce: 'So.won',
    meaning: 'Wish (n.)',
    sentence: [
      '촛불을 끄기 전에 소원을 빌어.',
      'Make a wish before you blow out the candle.'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 5,
    word: '시장',
    pronounce: 'Si.jang',
    meaning: 'Market ; marketplace (n.)',
    sentence: [
      '우리는 시장에서 과일과 채소를 산다.',
      'We buy our fruit and vegetables at the market.'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 6,
    word: '대답하다',
    pronounce: 'Dae.dap.ha.da',
    meaning: 'Answer (v.)',
    sentence: [
      '그녀는 어렵지 않게 내 질문에 대답했다.',
      'She answered my question without difficulty.'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 7,
    word: '소중하다',
    pronounce: 'So.jung.ha.da',
    meaning: 'Precious ; valuable ; priceless (adj.)',
    sentence: [
      '내게 가장 소중한 것은 가족이예요.',
      'The most important thing to me is family.'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 8,
    word: '동물',
    pronounce: 'Dong.mul',
    meaning: 'Animal (n.)',
    sentence: [
      '반려동물을 키운다면 어떤 동물을 키우고 싶어요?',
      'If you could raise a pet, what kind of animal would you like to have?'
    ],
  ),
  Vocab(
    lessonId: '2',
    count: 9,
    word: '오징어',
    pronounce: 'O.jing.eo',
    meaning: 'Squid (n.)',
    sentence: ['"오징어" 게임 봤어요?', 'Have you watched "Squid Game"?'],
  ),
  Vocab(
    lessonId: '2',
    count: 10,
    word: '동네',
    pronounce: 'Dong.ne',
    meaning: 'Neighborhood (n.)',
    sentence: ['그들은 같은 동네에 산다.', 'They live in the same neighborhood.'],
  ),
  Vocab(
    lessonId: '3',
    count: 1,
    word: '오전',
    pronounce: 'O.chon',
    meaning: 'Morning ; a.m. (n.)',
    sentence: ['지금 시간이 오전 7시 10분이다.', 'It is ten after seven in the morning.'],
  ),
  Vocab(
    lessonId: '3',
    count: 2,
    word: '오후',
    pronounce: 'O.hu',
    meaning: 'Afternoon ; p.m. (n.)',
    sentence: ['오후에 그들은 쇼핑을 갔다.', 'In the afternoon they went shopping.'],
  ),
  Vocab(
    lessonId: '3',
    count: 3,
    word: '전기',
    pronounce: 'Jeon.gi',
    meaning: 'Electricity (n.)',
    sentence: [
      '전기 장치에 문제가 있다.',
      'There is a problem with the electrical device.'
    ],
  ),
  Vocab(
    lessonId: '3',
    count: 4,
    word: '과일',
    pronounce: 'Gwa.il',
    meaning: 'Fruit (n.)',
    sentence: ['어떤 과일을 좋아해?', 'What kind of fruit do you like?'],
  ),
  Vocab(
    lessonId: '3',
    count: 5,
    word: '소매',
    pronounce: 'So.mae',
    meaning: 'Sleeve (n.)',
    sentence: ['그녀는 소매를 짧게 걷었다.', 'She rolled up (shortened) the sleeves.'],
  ),
  Vocab(
    lessonId: '3',
    count: 6,
    word: '끓이다',
    pronounce: 'Kkeu.ri.da',
    meaning: 'Boil ; shimmer (v.)',
    sentence: ['라면을 끓일까요?', 'Shall I make (boil) ramyun?'],
  ),
  Vocab(
    lessonId: '3',
    count: 7,
    word: '빠르다',
    pronounce: 'Ppa.reu.da',
    meaning: 'Fast (adj.)',
    sentence: ['기차로 가는 것이 더 빠르다.', 'It is faster to go by train.'],
  ),
  Vocab(
    lessonId: '3',
    count: 8,
    word: '느리다',
    pronounce: 'Neu.ri.da',
    meaning: 'Slow (adj.)',
    sentence: ['인터넷이 너무 느려요.', 'The internet is too slow.'],
  ),
  Vocab(
    lessonId: '3',
    count: 9,
    word: '구내식당',
    pronounce: 'Gu.nae.sik.dang',
    meaning: 'Cafeteria (n.)',
    sentence: [
      '학생들이 구내식당에서 식사를 하고있다.',
      'The students are eating in the cafeteria.'
    ],
  ),
  Vocab(
    lessonId: '3',
    count: 10,
    word: '고르다',
    pronounce: 'Go.reu.da',
    meaning: 'Choose ; pick ; select (n.)',
    sentence: [
      '나는 민트, 우유, 그리고 코코아 맛의 아이스크림을 골랐어.',
      'I choose the mint, milk, and cocoa-flavored icecream.'
    ],
  ),
  Vocab(
    lessonId: '4',
    count: 1,
    word: '시',
    pronounce: 'Si',
    meaning: 'Time ; hour (n.)',
    sentence: [
      '그 회의는 정각 2시에 시작된다.',
      'The meeting starts at 2 o\'clock precisely.'
    ],
  ),
  Vocab(
    lessonId: '4',
    count: 2,
    word: '날',
    pronounce: 'Nal',
    meaning: 'Day (n.)',
    sentence: [
      '우리는 더운 날에 레모네이드를 마시는 걸 좋아해요.',
      'We like to drink lemonade on a hot day.'
    ],
  ),
  Vocab(
    lessonId: '4',
    count: 3,
    word: '놓다',
    pronounce: 'No.ta',
    meaning: 'Put (v.)',
    sentence: ['그녀는 책을 테이블 위에 놓았다.', 'She put the book on the table.'],
  ),
  Vocab(
    lessonId: '4',
    count: 4,
    word: '입',
    pronounce: 'Ip',
    meaning: 'Mouth (n.)',
    sentence: ['입을 벌리고 "아-" 하세요.', 'Open your mouth and say "aaa-".'],
  ),
  Vocab(
    lessonId: '4',
    count: 5,
    word: '생물학',
    pronounce: 'Saeng.mur.hak',
    meaning: 'Biology (n.)',
    sentence: ['생물학은 내가 좋아하는 과목이다.', 'Biology is my favourite subject.'],
  ),
  Vocab(
    lessonId: '4',
    count: 6,
    word: '길다',
    pronounce: 'Gil.da',
    meaning: 'Long (adj.)',
    sentence: ['코끼리는 코가 길다.', 'An elephant has a long trunk.'],
  ),
  Vocab(
    lessonId: '4',
    count: 7,
    word: '고향',
    pronounce: 'Go.hyang',
    meaning: 'Hometown ; home (n.)',
    sentence: ['크리스마스 때 고향 가세요?', 'Are you going home for Christmas?'],
  ),
  Vocab(
    lessonId: '4',
    count: 8,
    word: '초코릿',
    pronounce: 'Cho.ko.lit',
    meaning: 'Chocolate (n.)',
    sentence: ['초콜릿 아이스크림 하나 주세요.', 'One chocolate ice cream, please.'],
  ),
  Vocab(
    lessonId: '4',
    count: 9,
    word: '동갑',
    pronounce: 'Dong.gap',
    meaning: 'Same age (n.)',
    sentence: ['우린 동갑이네요!', 'We are the same age!'],
  ),
  Vocab(
    lessonId: '4',
    count: 10,
    word: '왕관',
    pronounce: 'Wang.gwan',
    meaning: 'Crown (n.)',
    sentence: ['이 왕관은 금으로 만들었어요.', 'This crown is made of gold.'],
  ),
  Vocab(
    lessonId: '5',
    count: 1,
    word: '시간표',
    pronounce: 'Si.gan.pyo',
    meaning: 'Schedule ; timetable (n.)',
    sentence: [
      '우리는 학기마다 시간표가 다르다.',
      'We have different timetable for each semester.'
    ],
  ),
  Vocab(
    lessonId: '5',
    count: 2,
    word: '자다',
    pronounce: 'Ja.da',
    meaning: 'Sleep (v.)',
    sentence: ['간밤에 아주 잘 잤어요.', 'I slept very well last night.'],
  ),
  Vocab(
    lessonId: '5',
    count: 3,
    word: '열 ',
    pronounce: 'Yeol',
    meaning: 'Fever ; hear (n.)',
    sentence: ['열이 나고 목도 아프다.', 'I have a fever, and my throat is sore.'],
  ),
  Vocab(
    lessonId: '5',
    count: 4,
    word: '생각하다',
    pronounce: 'Saeng.gak.ha.da',
    meaning: 'Think (v.)',
    sentence: ['결정하기 전에 다시 생각해봐.', 'Think twice before you decide.'],
  ),
  Vocab(
    lessonId: '5',
    count: 5,
    word: '램프',
    pronounce: 'Laem.peu',
    meaning: 'Lamp (n.)',
    sentence: ['여자가 램프를 켜고 있다.', 'She is turning on the lamp.'],
  ),
  Vocab(
    lessonId: '5',
    count: 6,
    word: '인터넷',
    pronounce: 'In.teo.net',
    meaning: 'Internet (n.)',
    sentence: [
      '내 인터넷 접속에 문제가 있어.',
      'I am having problems with my Internet connection.'
    ],
  ),
  Vocab(
    lessonId: '5',
    count: 7,
    word: '의자',
    pronounce: 'Eui.ja',
    meaning: 'Chair (n.)',
    sentence: [
      '이 방에는 침대 하나와 테이블 하나 그리고 의자 두 개가 있다.',
      'There is a bed, a table, and two chairs in this room.'
    ],
  ),
  Vocab(
    lessonId: '5',
    count: 8,
    word: '지우개',
    pronounce: 'Ji.u.gae',
    meaning: 'Eraser (n.)',
    sentence: ['지우개 좀 잠깐 빌릴 수 있을까요?', 'Can I borrow your eraser for a moment?'],
  ),
  Vocab(
    lessonId: '5',
    count: 9,
    word: '공포',
    pronounce: 'Gong.po',
    meaning: 'Horror (n.)',
    sentence: ['나는 공포 영화를 좋아해요.', 'I like horror movies.'],
  ),
  Vocab(
    lessonId: '5',
    count: 10,
    word: '봉투',
    pronounce: 'Bong.tu',
    meaning: 'Envelope (n.)',
    sentence: ['그는 봉투에 우표를 붙였다.', 'He put a stamp on the envelope.'],
  ),
];
